### ISSUE TITLE
When you pass trough the border between Zones it will give you wallhack.

### ISSUE THREAD

**Issue by BerserkerBG** [stijn-volckaert/udemo#131]
During demoplay, if you pass trough zones, it will briefly give you vision of the whole level.
![Screenshot_42](https://github.com/stijn-volckaert/udemo/assets/58362332/ad2c614e-bda9-47c7-a8c2-9e6294dd7d52)
![Screenshot_38](https://github.com/stijn-volckaert/udemo/assets/58362332/3cd0febc-99ea-49a7-ac3a-a09bfab9cb5c)

Video example:

https://github.com/stijn-volckaert/udemo/assets/58362332/9cc62930-bd6a-44d7-81e6-7999e676721e

Demo example:
[ZoneBug.zip](https://github.com/stijn-volckaert/udemo/files/11995231/ZoneBug.zip)

This bug happens on all renderers I could try (Software, D3D, D3D9, OpenGL, xOpenGL)

**Comment by SeriousBuggie** [comment]
What render you use? What about other renders? This happen in all renders or in particular one?

**Comment by BerserkerBG** [comment]
> What render you use? What about other renders? This happen in all renders or in particular one?

Yes, it happens with every renderer. I updated my post.

**Comment by SeriousBuggie** [comment]
It is engine/render bug, not related to demo.
In demo it much more easy trigger, since demo store location rounded, and bug trigger by very precise values. You need be exactly on super cut, which almost impossible in real game. But in game your coordinates rounded on save into file, so when demo playback, it trigger bug much more often.

**Comment by SeriousBuggie** [comment]
I close this issue in favor for new one, which open in patch repo.
