### ISSUE TITLE
Allow game tweaking and modding when playing back demo

### ISSUE THREAD

**Issue by BerserkerBG** [stijn-volckaert/udemo#16]
During demo playback, the game does not allow some of the tweaking commands to make the game look different. Testing the following console command works in offline single player, but when playing back a demo, even if it is an offline demo - it does not allow you to tweak and modify it using some of the console commands.
![Screenshot_1888](https://user-images.githubusercontent.com/58362332/149717208-826d7cce-9abc-40c3-995f-73982be0ba05.png)

For this specific purpose, I wanted to change the shock to a custom one for a frag movie.

**Comment by SeriousBuggie** [comment]
Can't find line " be modified" in open sources or demo source. So it goes be closed part of engine, and introduced after v432.

Also i guess this basic check for any client during net play, or you can cheat with macros.

Since demoplay in some sort net play where you act like client, this protection apply here too. Possible it need modify this rule in engine, for exclude demoplay.

But in general it dangerous and can ruin demoplay, ESP if there used a lot client-side logic.

Even change mesh can ruin animation-driven logic.

**Comment by SeriousBuggie** [comment]
We have talk in discord in a while back. This is still problem? If no, please close ticket.
