### ISSUE TITLE
View Bob doesn't work on demo playback

### ISSUE THREAD

**Issue by BerserkerBG** [stijn-volckaert/udemo#19]
Live gameplay vs demoplay comparison

https://user-images.githubusercontent.com/58362332/152546719-a1d18d48-1080-49c8-b063-6f3a906c3b01.mp4

(Offline tests)

**Comment by prom6** [comment]
I dont even have the walking sounds when playing a demo
maybe it has something to do with the basic functionality of the demoplayback class, something like first person is only emulated on top of the third person actor otherwise there would be walkbob and sounds by default
cant be a UT Pure issue, cause its also not working on demos recorded offline without Pure

edit: its even not working when recording with the original built in demorecorder, so I would say this would be a feature request
