### ISSUE TITLE
Demo manager can open out of screen

### ISSUE THREAD

**Issue by SeriousBuggie** [stijn-volckaert/udemo#28]
Sometimes Demo manager open as
![scr_1681069038](https://user-images.githubusercontent.com/70026933/230793682-bee454ea-8597-4255-b022-c4538c5757f7.png)
This make it unusable.

I think need ensure coordinates not goes negative on open.

Look like somehow it try center around point `(0,0)`.

**Comment by garry-ut99** [comment]
> **Sometimes** Demo manager open as

The **sometimes** for me was as follow:

- I noticed it was happening only occasionally when launching game normally: `UnrealTournament.exe`
- however, then I noticed it was happening almost every time when launching game with appended a server to join, for example: `UnrealTournament.exe 139.162.235.20:7777`, like it had no time for initialize properly

**Comment by SeriousBuggie** [comment]
Still happens.

Way for reproduce:
1. Start UT with server on autocoonect (direct addr4ess or in exec file).
2. Wait connect to server and enter to it.
3. Disconnect from server by press button with bind "Disconnect".
4. Open demo manager via menu.

**Comment by garry-ut99** [comment]
The same issue happens with ChatDiamond mutator, which opens it's window between switching the levels on the server and sometimes it opens outside the screen.
Is it fixed in 469d for ChatDiamond too? 
Is it fixed for all mutators which suffer the same bug?


![bug22](https://github.com/stijn-volckaert/udemo/assets/72945564/95efa9fa-d8a9-4465-8eaf-db6a367f6715)
